"""init tables

Revision ID: 0bfa3e99a5d2
Revises: 
Create Date: 2021-10-26 03:19:33.393654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bfa3e99a5d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('storage_width', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('sid', sa.Integer(), nullable=True),
    sa.Column('rid', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash')
    )
    op.create_index(op.f('ix_player_sid'), 'player', ['sid'], unique=False)
    op.create_index(op.f('ix_player_username'), 'player', ['username'], unique=True)
    op.create_table('world',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('summation_mode', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_world_name'), 'world', ['name'], unique=True)
    op.create_table('item_def',
    sa.Column('item_group_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cls', sa.Integer(), nullable=False),
    sa.Column('dex', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['item_group_id'], ['item_group.id'], ),
    sa.PrimaryKeyConstraint('item_group_id', 'id')
    )
    op.create_table('realm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('item_group_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_group_id'], ['item_group.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['world.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_realm_name'), 'realm', ['name'], unique=True)
    op.create_table('account',
    sa.Column('realm_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_get_at', sa.DateTime(), nullable=False),
    sa.Column('last_set_at', sa.DateTime(), nullable=True),
    sa.Column('game_version', sa.Integer(), nullable=True),
    sa.Column('squad_tag', sa.String(length=3), nullable=True),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('max_authority_reached', sa.Float(), nullable=True),
    sa.Column('authority', sa.Float(), nullable=True),
    sa.Column('job_points', sa.Float(), nullable=True),
    sa.Column('faction', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('alive', sa.Boolean(), nullable=True),
    sa.Column('soldier_group_id', sa.Integer(), nullable=True),
    sa.Column('soldier_group_name', sa.String(length=32), nullable=True),
    sa.Column('squad_size_setting', sa.Integer(), nullable=True),
    sa.Column('item0_index', sa.Integer(), nullable=True),
    sa.Column('item0_amount', sa.Integer(), nullable=True),
    sa.Column('item0_key', sa.String(length=32), nullable=True),
    sa.Column('item1_index', sa.Integer(), nullable=True),
    sa.Column('item1_amount', sa.Integer(), nullable=True),
    sa.Column('item1_key', sa.String(length=32), nullable=True),
    sa.Column('item2_index', sa.Integer(), nullable=True),
    sa.Column('item2_amount', sa.Integer(), nullable=True),
    sa.Column('item2_key', sa.String(length=32), nullable=True),
    sa.Column('item4_index', sa.Integer(), nullable=True),
    sa.Column('item4_amount', sa.Integer(), nullable=True),
    sa.Column('item4_key', sa.String(length=32), nullable=True),
    sa.Column('item5_index', sa.Integer(), nullable=True),
    sa.Column('item5_amount', sa.Integer(), nullable=True),
    sa.Column('item5_key', sa.String(length=32), nullable=True),
    sa.Column('kills', sa.Integer(), nullable=True),
    sa.Column('deaths', sa.Integer(), nullable=True),
    sa.Column('time_played', sa.Integer(), nullable=True),
    sa.Column('player_kills', sa.Integer(), nullable=True),
    sa.Column('teamkills', sa.Integer(), nullable=True),
    sa.Column('longest_kill_streak', sa.Integer(), nullable=True),
    sa.Column('targets_destroyed', sa.Integer(), nullable=True),
    sa.Column('vehicles_destroyed', sa.Integer(), nullable=True),
    sa.Column('soldiers_healed', sa.Integer(), nullable=True),
    sa.Column('times_got_healed', sa.Integer(), nullable=True),
    sa.Column('distance_moved', sa.Float(), nullable=True),
    sa.Column('shots_fired', sa.Integer(), nullable=True),
    sa.Column('throwables_thrown', sa.Integer(), nullable=True),
    sa.Column('rank_progression', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['realm_id'], ['realm.id'], ),
    sa.ForeignKeyConstraint(['world_id'], ['world.id'], ),
    sa.PrimaryKeyConstraint('realm_id', 'player_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account')
    op.drop_index(op.f('ix_realm_name'), table_name='realm')
    op.drop_table('realm')
    op.drop_table('item_def')
    op.drop_index(op.f('ix_world_name'), table_name='world')
    op.drop_table('world')
    op.drop_index(op.f('ix_player_username'), table_name='player')
    op.drop_index(op.f('ix_player_sid'), table_name='player')
    op.drop_table('player')
    op.drop_table('item_group')
    # ### end Alembic commands ###
